### ISSUE TITLE
Can get latest release

### ISSUE THREAD

**Issue by kcoderhtml** [spicetify/cli#3227]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.48.405.gf2c48e6f
- Spicetify version: v2.36.14
```

### 📝 Description

Run `spicetify restore backup apply`

get error:

```bash
warning Cannot fetch version tag for CSS mappings
err: Get "https://api.github.com/repos/spicetify/cli/releases/latest": dial tcp: lookup api.github.com on [::1]:53: read udp [::1]:43792->[::1]:53: read: connection refused
info Fetching remote CSS map for newer compatible tag version: 2.36.14
info Cannot fetch remote CSS map. Using local CSS map instead...
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/spicetify/cli/src/preprocess.exposeAPIs_main({0xc001d60000, 0x2d2941})
        github.com/spicetify/cli/src/preprocess/preprocess.go:560 +0x573
github.com/spicetify/cli/src/preprocess.Start.func1.1({0xc001a8c000, 0x2d1f7f})
        github.com/spicetify/cli/src/preprocess/preprocess.go:103 +0x192
github.com/spicetify/cli/src/utils.ModifyFile({0xc00027d740, 0x2f}, 0xc0000e59e8)
        github.com/spicetify/cli/src/utils/utils.go:221 +0xbc
github.com/spicetify/cli/src/preprocess.Start.func1({0xc00027d740, 0x2f}, {0x7c4928?, 0xc0001b2000?}, {0x0?, 0x0?})
        github.com/spicetify/cli/src/preprocess/preprocess.go:91 +0x145
path/filepath.walk({0xc00027d740, 0x2f}, {0x7c4928, 0xc0001b2000}, 0xc0000e5ca8)
        path/filepath/path.go:478 +0x105
path/filepath.walk({0xc0001c55f0, 0x27}, {0x7c4928, 0xc0001b3860}, 0xc0000dfca8)
        path/filepath/path.go:502 +0x254
path/filepath.Walk({0xc0001c55f0, 0x27}, 0xc0000e3ca8)
        path/filepath/path.go:560 +0x66
github.com/spicetify/cli/src/preprocess.Start({0x7bfdd8, 0x7}, {0xc00002e3f0?, 0x22?}, {0x0?, 0xc3?, 0x1?, 0x0?})
        github.com/spicetify/cli/src/preprocess/preprocess.go:85 +0x2c6
github.com/spicetify/cli/src/cmd.Backup({0x7bfdd8, 0x7})
        github.com/spicetify/cli/src/cmd/backup.go:68 +0x3fc
main.main()
        github.com/spicetify/cli/spicetify.go:263 +0xaf1
```

I can get the latest release from that URL when opened with my browser, oddly.

The line likely causing this is just a simple get: https://github.com/spicetify/cli/blob/e3ec2ecc61e04f248ca185141eb7977ce3c44adb/src/utils/vcs.go#L16

Running a curl also returns a valid JSON response.

**Comment by rxri** [comment]
Install latest version with install script from our docs. Did you run `spicetify upgrade` though to update spicetify? The error you're showing is because you're trying to run old version of spicetify on newer unsupported spotify version by it

**Comment by rxri** [comment]
oh and that tcp error is because you have `api.github.com` redirected to localhost `[::1]`. Fault is on your end and network/hosts file idk
![image](https://github.com/user-attachments/assets/2a4b1f47-5356-47bd-a51a-354c2f23a57b)

**Comment by kcoderhtml** [comment]
ah. okay thnks!
